const nodemailer = require('nodemailer');

async function sendEmail(link, user) {
    try {
        const transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: process.env.ADMIN_EMAIL,
                pass: process.env.ADMIN_PASSWORD
            }
        });
        const s1 = ' <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> <html data-editor-version="2" class="sg-campaigns" xmlns="http://www.w3.org/1999/xhtml"> <head> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1"> <!--[if !mso]><!--> <meta http-equiv="X-UA-Compatible" content="IE=Edge"> <!--<![endif]--> <!--[if (gte mso 9)|(IE)]> <xml> <o:OfficeDocumentSettings> <o:AllowPNG/> <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml> <![endif]--> <!--[if (gte mso 9)|(IE)]> <style type="text/css"> body {width: 600px;margin: 0 auto;} table {border-collapse: collapse;} table, td {mso-table-lspace: 0pt;mso-table-rspace: 0pt;} img {-ms-interpolation-mode: bicubic;} </style> <![endif]--> <style type="text/css"> body, p, div { font-family: inherit; font-size: 14px; } '
        const s2 = 'body { color: #000000; } body a { color: #1188E6; text-decoration: none; } p { margin: 0; padding: 0; } table.wrapper { width: 100% !important; table-layout: fixed; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: 100%; -moz-text-size-adjust: 100%; -ms-text-size-adjust: 100%; } img.max-width { max-width: 100% !important; } .column.of-2 { width: 50%; } .column.of-3 { width: 33.333%; } .column.of-4 { width: 25%; } @media screen and (max-width:480px) { .preheader .rightColumnContent, .footer .rightColumnContent { text-align: left !important; } .preheader .rightColumnContent div, .preheader .rightColumnContent span, .footer .rightColumnContent div, .footer .rightColumnContent span { text-align: left !important; } .preheader .rightColumnContent, .preheader .leftColumnContent { font-size: 80% !important; padding: 5px 0; } table.wrapper-mobile { width: 100% !important; table-layout: fixed; } img.max-width { height: auto !important; max-width: 100% !important; } a.bulletproof-button { display: block !important; width: auto !important; font-size: 80%; padding-left: 0 !important; padding-right: 0 !important; } .columns { width: 100% !important; } .column { display: block !important; width: 100% !important; padding-left: 0 !important; padding-right: 0 !important; margin-left: 0 !important; margin-right: 0 !important; } } </style> <!--user entered Head Start-->'
        const s3 = '<link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet"> <style> body { font-family: \'Muli\', sans-serif; } </style> <!--End Head user entered--> </head> <body> <center class="wrapper" data-link-color="#1188E6" data-body-style="font-size:14px; font-family:inherit; color:#000000; background-color:#2855AE;"> <div class="webkit"> <table cellpadding="0" cellspacing="0" border="0" width="100%" class="wrapper" bgcolor="#2855AE"> <tbody> <tr> <td valign="top" bgcolor="#FFFFFF" width="100%"> <table width="100%" role="content-container" class="outer" align="center" cellpadding="0" cellspacing="0" border="0"> <tbody> <tr> <td width="100%"> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tbody> <tr> <td> <!--[if mso]> <center> <table><tr><td width="600"> <![endif]--> <table width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%; max-width:600px;" align="center"> <tbody> <tr> <td role="modules-container" style="padding:0px 0px 0px 0px; color:#000000; text-align:left;" bgcolor="#2855AE" width="100%" align="left"> <table class="module preheader preheader-hide" role="module" data-type="preheader" border="0" cellpadding="0" cellspacing="0" width="100%" style="display: none !important; mso-hide: all; visibility: hidden; opacity: 0; color: transparent; height: 0; width: 0;"> <tbody> <tr> <td role="module-content"> <p></p> </td> </tr> </tbody> </table> <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" role="module" data-type="columns"'
        const s4 = 'style="padding:30px 20px 30px 20px;" bgcolor="#2855AE"> <tbody> <tr role="module-content"> <td height="100%" valign="top"> <table class="column" width="540" style="width:540px; border-spacing:0; border-collapse:collapse; margin:0px 10px 0px 10px;" cellpadding="0" cellspacing="0" align="left" border="0" bgcolor=""> <tbody> <tr> <td style="padding:0px;margin:0px;border-spacing:0;"> <table class="wrapper" role="module" data-type="image" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="72aac1ba-9036-4a77-b9d5-9a60d9b05cba"> <tbody> <tr> <td style="font-size:6px; line-height:10px; padding:0px 0px 0px 0px;" valign="top" align="center"> <svg xmlns="http://www.w3.org/2000/svg" width="211.968" height="211.821" viewBox="0 0 211.968 211.821"> <g transform="translate(-1.984 -1.5)"> <path d="M1.984,93.09a81.009,81.009,0,0,1,81.01-81.01V93.09Z" transform="translate(0 39.221)" fill="#345fb4" /> <path d="M1.984,29.29a81.009,81.009,0,0,0,81.01,81.01V29.29Z" transform="translate(0 103.021)" fill="#6789ca" /> <path d="M100.2,29.29A81.009,81.009,0,0,1,19.195,110.3V29.29Z" transform="translate(63.8 103.021)" fill="#345fb4" /> <path d="M142.823,62.326A60.826,60.826,0,0,1,82,123.151H21.172V62.326a60.826,60.826,0,1,1,121.651,0Z" transform="translate(71.13 0)" fill="#ff7917" /> </g> </svg> </td> </tr> </tbody> </table> <table class="module" role="module" data-type="spacer" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="331cde94-eb45-45dc-8852-'
        const s5 = 'b7dbeb9101d7"> <tbody> <tr> <td style="padding:0px 0px 20px 0px;" role="module-content" bgcolor=""> </td> </tr> </tbody> </table> <table class="wrapper" role="module" data-type="image" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="d8508015-a2cb-488c-9877-d46adf313282"> </table> <table class="module" role="module" data-type="spacer" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="27716fe9-ee64-4a64-94f9-a4f28bc172a0"> <tbody> <tr> <td style="padding:0px 0px 30px 0px;" role="module-content" bgcolor=""> </td> </tr> </tbody> </table> <table class="module" role="module" data-type="text" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="948e3f3f-5214-4721-a90e-625a47b1c957" data-mc-module-version="2019-10-22"> <tbody> <tr> <td style="padding:50px 30px 18px 30px; line-height:36px; text-align:inherit; border-radius:10px; background-color:#ffffff;" height="100%" valign="top" bgcolor="#2855AE" role="module-content"> <div> <div style="font-family: inherit; text-align: center"> <span style="font-size: 43px">Here`s your link!!&nbsp;</span></div> <div></div> </div> </td> </tr> </tbody> </table> <table class="module" role="module" data-type="text" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="a10dcb57-ad22-4f4d-b765-1d427dfddb4e" data-mc-module-version="2019-10-22"> <tbody> <tr> <td style="padding:18px 30px 18px 30px; line-height:22px; '
        const s6 = 'text-align:inherit; border-radius:10px; background-color:#ffffff;" height="100%" valign="top" bgcolor="#2855AE" role="module-content"> <div> <div style="font-family: inherit; text-align: center"> <span style="font-size: 18px">Please verify your email address</span><span style="color: #000000; font-size: 18px; font-family: arial,helvetica,sans-serif"> to get access to the application WCE Event Manager</span><span style="font-size: 18px">.</span> </div> <div style="font-family: inherit; text-align: center"> <div></div> </div> </td> </div> </tr> </tbody> </table> <table class="module" role="module" data-type="spacer" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="7770fdab-634a-4f62-a277-1c66b2646d8d"> <tbody> <tr> <td style="padding:0px 0px 20px 0px;" role="module-content" bgcolor="#2855AE"> </td> </tr> </tbody> </table> <table border="0" cellpadding="0" cellspacing="0" class="module" data-role="module-button" data-type="button" role="module" style="table-layout:fixed;" width="100%" data-muid="d050540f-4672-4f31-80d9-b395dc08abe1"> <tbody> <tr> <td align="center" bgcolor="#2855AE" class="outer-td" style="padding:0px 0px 0px 0px;"> <table border="0" cellpadding="0" cellspacing="0" class="wrapper-mobile" style="text-align:center;"> <tbody> <tr> <td align="center" bgcolor="#ffbe00" class="inner-td" style="border-radius:6px; font-size:16px; text-align:center; background-color:inherit;"> <a href="https://walchand-event-organizer.herokuapp.com/verifyemail/' + link + '" style="background-color:#ff7917; border: 2px solid #ff7917; border-color:#ff7917; border-radius:12px; border-width:1px; color:#000000; display:inline-block; font-size:14px; font-weight:normal; letter-spacing:0px; line-height:normal; padding:8px 25px 8px 30px; text-align:center; text-decoration:none; border-style:solid; font-family:inherit;" target="_blank">Verify Email Now</a> </td> </tr> </tbody> </table> </td> </tr> </tbody> </body> </html>'
        const mailOptions = {
            from: "wceeventmanager@gmail.com",
            to: user.email,
            subject: "Verify Your Email",
            html: s1 + s2 + s3 + s4 + s5 + s6 
        }
    
        transporter.sendMail(mailOptions, function (err, data) {
            if(err){
                console.log(err);
            }
            else{
                console.log('Email Sent successfully');
                res.status(201)
            }
        });
    }
    catch (error) {
        console.log(error);
        res.status(400).send(error);
    }
}

module.exports = sendEmail;



